spring:
  profiles:
    active: dev

  liquibase:
    change-log: 'classpath:db/changelog/db.changelog-master.xml'


resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 5
      waitDurationInOpenState: 10000
      failureRateThreshold: 5
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
  instances:
    GMaps:
      baseConfig: default
